### ISSUE TITLE
lein run throwing exception

### ISSUE THREAD

**Issue by MTrost** [lambdaisland/rolodex-gui#1]
Hi plexus

I just tried to work through Ring pt. 2 but `lein run` throws an exception.

It retrieves many packages but then it complains:
```
Exception in thread "main" java.lang.ClassNotFoundException: javax.xml.bind.DatatypeConverter, compiling:(cljs/closure.clj:1:1)
```

I'm on Leiningen 2.9.1, Java 9.0.4, Clojure 1.10.1 and Ubuntu 18.04.

Do you know if I can fix that on my end?

as an aside: great videos so far!

**Comment by plexus** [comment]
Hi MTrost,

Please pull from master, I've updated some dependencies to fix this and another issue. This one is due to the new module system introduced in Java 9. Because of that the java.xml.bind API is no longer available out of the box, you need to enable the module or pull it in as extra dependencies. This is fixed in the latest version of Figwheel and ClojureScript.

**Comment by MTrost** [comment]
It works, thank you for the quick fix!
